name: openkit_dart
description: OpenKit-Dart reference implementation for Dynatrace
version: 1.0.0
homepage: https://github.com/your-username/openkit-dart

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.0

flutter:
  # This section identifies this package as a Flutter plugin
  plugin:
    platforms:
      android:
        package: com.example.openkit_dart
        pluginClass: OpenkitDartPlugin
      ios:
        pluginClass: OpenkitDartPlugin
      web:
        pluginClass: OpenkitDartWeb
        fileName: openkit_dart_web.dart
      windows:
        pluginClass: OpenkitDartWindowsPlugin
      macos:
        pluginClass: OpenkitDartMacosPlugin
      linux:
        pluginClass: OpenkitDartLinuxPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each font entry should have a "family" key with
  # the font family name, and a "fonts" key with a list giving the asset
  # and other descriptors for the font. For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
